name = "uwaga-kawa-cms"
main = "src/worker.js"
compatibility_date = "2024-11-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "uwaga-kawa-db"
database_id = "436b1735-7492-457d-a43c-db7e7d4132c3"

# Zmienne Å›rodowiskowe
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-secret-key-change-in-production"
